---

- name: Configure zabbix userparameters available by vcgencmd
  include_role:
    name: zabbix-agent
    tasks_from: userparameter
  vars:
    zabbix_agent__userparameter:
      name: usbip_server
      userparameters:
        - key: usbip_server.missing_devices
          command: /usr/bin/env bash -c "source {{ usbip_server__configuration_file }} && exported_devices=\$(/usr/bin/env usbip list --parsable --remote=127.0.0.1 | grep --extended-regexp '^\s+[0-9\.-]+:') && for device in \$DEVICES; do if ! echo \"\${exported_devices}\" | grep --quiet \"\${device}\"; then echo -n \"\${device} \"; fi; done"
          comment: Get list of missing exported usb devices ids
      state: present
  tags: ['usbip-server', 'usbip-server-monitoring']
